### ISSUE TITLE
where to put api key?

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [RohitSurwase/AAC-MVI-Architecture#3]
where to put api key?

**Comment by RohitSurwase** [comment]
Sorry for replying so late. I haven't been notified of the issue.

So, you can keep your key inside Global **gradle.properties** file
`myNewsApiPrivateKey = "YOUR_API_KEY"`

Or alternatively you can simply open App level build.gradle.kts file and replace **myNewsApiPrivateKey** with your API KEY.
`buildConfigField("String", "NewsApiKey", "YOUR_API_KEY")`

If you have any doubts, please let me know.
